version: "3"
services:
  #PHP Service
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: php:7.2-fpm
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8087:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: stock_flutter_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USERNAME: flutter
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql/my.conf:/etc/mysql/my.conf
    networks:
      - app-network

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stock_flutter_db
      - MYSQL_USERNAME=flutter
      - MYSQL_PASSWORD=password
      - PMA_HOST=db
    ports:
      - 8089:80
    depends_on:
      - db
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
